# -*- coding: utf-8 -*-
"""dataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9M74Ga9oXNQz4rNBxUUAZkJYj5a7Ykx

# Thales Callidus 2024
En primera instancia, se revisaron los datos provenientes del repositorio público de conjuntos de datos proporcionados por el gobierno mexicano ('https://archivo.datos.cdmx.gob.mx/FGJ/carpetas/carpetasFGJ_acumulado_2024_09.csv') con la intención de crear un dataframe manipulable mediante la librería python pandas y así poder revisar la congruencia de los datos, así como la relevancia de sus variables para el fin de este proyecto.

Para evaluar la correlación entre las variables se realizó un análisis en minitab mediante el cuál se realizó la ingeniería de características necesaria para eliminar del dataframe las columnas menos significativas, dentro de las cuales se eliminaron las variables de “anio_hecho”, “competencia”, “unidad_investigacion”, “agencia”, etc.

El procesamiento de limpieza de datos consistió en eliminar del dataframe las columnas identificadas mediante el análisis en Minitab, se eliminaron los registros que contenían celdas vacías en alguna columna con gran significancia y por último se borraron los renglones vacíos derivados de malformaciones en la estructura de las base de datos.

Inclusión de librerias a utilizar
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Lectura de archivo .csv con datos de interés"""

df = pd.read_csv('https://archivo.datos.cdmx.gob.mx/FGJ/carpetas/carpetasFGJ_acumulado_2024_09.csv')

"""Creación de dataframe manipulable y su descripción"""

df = pd.DataFrame(df)
print(df.info())

"""Estadística básica de algunas variables de interés"""

print(df.describe())

"""Muestra ejemplo de la base de datos y su estructura"""

df.head(25)

"""Eliminación de espcaios y filas en blanco dentro del archivo"""

df['fiscalia'] = df['fiscalia'].map(lambda x: str(x).strip())

dd = df
print(dd.info())

"""Realizar limpieza de valores nulos"""

dd.dropna(subset=['fecha_hecho','hora_hecho','latitud', 'longitud'], inplace=True)

"""Eliminación de columnas poco significativas o de bajo interés para el modelo"""

dd = dd.drop(['anio_inicio', 'mes_inicio', 'fecha_inicio', 'hora_inicio', 'competencia', 'colonia_catalogo', 'alcaldia_catalogo', 'municipio_hecho'], axis=1) #borrar columnas no significativas

"""Muestra del dataframe final"""

print(dd.info())